name: &name "QuartzNet5x5LS-En"
sample_rate: &sample_rate 16000
repeat: &repeat 1
dropout: &dropout 0.0
separable: &separable true
labels: &labels [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
         "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'",
         "á", "é", "í", "ó", "ú", "ñ", "ü"]

model:
  train_ds:
    manifest_filepath: /data/SPANISH_CV/train_manifest.jsonl
    sample_rate: 16000
    labels: *labels
    batch_size: 16
    num_workers: 8
    trim_silence: True
    max_duration: 16.7
    shuffle: False
    is_tarred: False
    tarred_audio_filepaths: null
    tarred_shard_strategy: "scatter"

  validation_ds:
    manifest_filepath: /data/SPANISH_CV/dev_manifest.jsonl
    sample_rate: 16000
    labels: *labels
    batch_size: 16
    num_workers: 4
    shuffle: False

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: "per_feature"
    window_size: 0.02
    sample_rate: *sample_rate
    window_stride: 0.01
    window: "hann"
    features: &n_mels 64
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001
    stft_conv: false

  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    rect_freq: 50
    rect_masks: 5
    rect_time: 120

  optim:
    name: novograd
    # _target_: nemo.core.optim.optimizers.Novograd
    lr: .001
    # optimizer arguments
    betas: [0.8, 0.5]
    weight_decay: 0.001

trainer:
  gpus: 1 # number of gpus
  max_epochs: 1
  max_steps: null # computed at runtime if not set
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  log_every_n_steps: 1  # Interval of logging.
  val_check_interval: 1.0 # check once per epoch .25 for 4 times per epoch

exp_manager:
  exp_dir: null
  name: *name
  create_tensorboard_logger: True
  create_checkpoint_callback: True

hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null
