name: speech_recognition
channels:
  - conda-forge
  - pytorch
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - cudatoolkit=10.1
  - pytorch=1.6.0
  - pytorch-lightning
  - torchaudio
  - wget
  - tqdm
  - numba
  - python-levenshtein
  - librosa
  - boto3
  - wandb
  - sagemaker-python-sdk
  - pip:
      - "util@git+https://git@github.com/dertilo/util.git#egg=util"
      - test_tube
