name: asr
channels:
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=10.1
  - pytorch
  - torchvision
  - pytorch-lightning
  - torchaudio
  - wget
  - tqdm
  - numba
  - python-levenshtein

